main: "io.github.mrsperry.worldhandler.Main"
name: "WorldHandler"
version: ${project.version}
description: "Allows handling of custom worlds"
api-version: "1.15"
commands:
  worlds:
    description: "Allows manipulation of custom worlds"
    usage: "/worlds [help | list | tp | create | info | settings | load | unload]"