rifts:
  enabled: true
  spawning:
    # Number of blocks away from a player a rift can spawn
    area: 50
    # Percentage to spawn
    chance: 25
    # How many seconds between spawn chance
    frequency: 60
    # Maximum number of rifts at a time
    max: 3
    size:
      # Radius: 25 blocks; Length: 5 minutes
      small:
        enabled: true
        max-monsters: 25
        length: 5
        radius: 25
      # Radius: 50 blocks; Length: 7 minutes
      medium:
        enabled: true
        max-monsters: 50
        length: 7
        radius: 50
      # Radius: 100 blocks; Length: 10 minutes
      large:
        enabled: true
        max-monsters: 75
        length: 10
        radius: 100
