main: io.github.mrsperry.rifts.Main
name: Rifts
version: 1.0.0
description: World-splitting rifts featuring a wide array of monsters to kill.
commands:
  rift:
    description: SMain rift command
    usage: /rift [spawn | stop | ids]
    permission: rifts.manage