main: io.github.mrsperry.rifts.Rifts
name: Rifts
version: 1.0.0
description: World-splitting rifts featuring a wide array of monsters to kill.
commands:
  spawnrift:
    description: Spawn a rift around a player
    usage: /spawnrift |radius=50| |player=Notch|
    permission: rifts.spawn
  endrift:
    description: End a rift within a radius or all rifts
    usage: /endrift [50 || -a]
    permission: rifts.end
  riftids:
    description: Get a list of all rift config IDs
    usage: /eriftids
    permission: rifts.spawn