main: "io.github.mrsperry.croptweaks.Main"
name: "CropTweaks"
version: ${plugin.version}
authors: ["dinner1111"]
description: "Allows the automatic harvesting and replanting of crops by right clicking them, at the cost of all seeds."
api-version: "1.15"