main: io.github.mrsperry.time.Main
name: Time
version: 1.0.0.0
authors: [dinner1111]
description: Records how much time you play.
commands:
  time:
    usage: /time [player name | server]
    description: Tells you how much time you or someone else has played