main: "io.github.mrsperry.time.Main"
name: "Time"
version: ${project.version}
authors: ["dinner1111"]
description: "Records how much time you play."
api-version: "1.15"
commands:
  time:
    usage: "/time [player name | server]"
    description: "Tells you how much time you or someone else has played"